tasks:
    - name: ec2_cloudwatch
      metrics:
          - aws_namespace: "AWS/EC2"
            aws_dimensions: [InstanceId]
            aws_dimensions_select:
                InstanceId: [$_target]
            aws_metric_name: CPUUtilization
            aws_statistics: [Average]

          - aws_namespace: "AWS/EC2"
            aws_dimensions: [InstanceId]
            aws_dimensions_select:
                InstanceId: [$_target]
            aws_metric_name: NetworkOut
            aws_statistics: [Average]
